[module]

[[module.mounts]]
source = "layouts"
target = "layouts"

[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "i18n"
target = "i18n"

[[module.mounts]]
source = "static"
target = "static"

[[module.mounts]]
source = "node_modules"
target = "assets/node_modules"

[[module.mounts]]
source = "node_modules/@fortawesome/fontawesome-free/webfonts"
target = "static/assets/css/webfonts"

[[module.mounts]]
source = "node_modules/@fontsource/anonymous-pro"
target = "static/assets/css/fontsource-anonymous-pro"

[[module.mounts]]
source = "node_modules/@fontsource/comfortaa"
target = "static/assets/css/fontsource-comfortaa"
