# Page settings

baseURL = "https://example.com"
languageCode = "en"
title = "Gabriele Lucci's resume"
theme = "hugo-devresume-theme"
enableRobotsTXT = true
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
author = "Gabriele Lucci"
description = "Gabriele Lucci's resume - english"

primaryColor = "#B75D69"
textPrimaryColor = "#292929"


[params.profile]
enable = true
name = "Gabriele Lucci"
tagline = "Web developer"
avatar = "avatar.png"


[params.contact]
enable = true

[[params.contact.list]]
icon = "fas fa-map-marked-alt"
url = ""
text = "Palestrina, RM"
[[params.contact.list]]
icon = "fas fa-envelope"
url = "mailto://gabriele@lucci.xyz"
text = "gabriele@lucci.xyz"
[[params.contact.list]]
icon = "fab fa-github"
url = "https://github.com/gabrielelucci"
text = "GitHub: gabrielelucci"
[[params.contact.list]]
icon = "fab fa-gitlab"
url = "https://github.com/gabrielelucci"
text = "GitLab.com: gabrielelucci"
[[params.contact.list]]
icon = "fab fa-telegram"
url = "https://telegram.me/gabrielelucci"
text = "Telegram: username"


[params.skills]
enable = true

[[params.skills.list]]
title = "Programming"
[[params.skills.list.items]]
details = "Python"
[[params.skills.list.items]]
details = "Javascript/Node.js"
[[params.skills.list.items]]
details = "Java/Android"

[[params.skills.list]]
title = "Web development"
[[params.skills.list.items]]
details = "Django / Flask"
[[params.skills.list.items]]
details = "Loopback v3"
[[params.skills.list.items]]
details = "uwsgi"
[[params.skills.list.items]]
details = "RDF / SPARQL"
[[params.skills.list.items]]
details = "Apache Solr / Elasticsearch"
[[params.skills.list.items]]
details = "Redis"
[[params.skills.list.items]]
details = "PostgreSQL / PostGIS"


[[params.skills.list]]
title = "Tooling"
[[params.skills.list.items]]
details = "Git"
[[params.skills.list.items]]
details = "GitLab (CI/CD) / GitHub"
[[params.skills.list.items]]
details = "Docker / docker-compose"
[[params.skills.list.items]]
details = "pandas / numpy"
[[params.skills.list.items]]
details = "IntelliJ/PyCharm"

[[params.skills.list]]
title = "Misc."
[[params.skills.list.items]]
details = "GNU/Linux"
[[params.skills.list.items]]
details = "Nginx / Caddy"
[[params.skills.list.items]]
details = "Rancher"


# [params.education]
# enable = true
#
# [[params.education.list]]
# degree = "MSc in Computer Science"
# university = "University College London"
# dates = "2010 - 2011"
# [[params.education.list]]
# degree = "BSc Maths and Physics"
# university = "Imperial College London"
# dates = "2007 - 2010"


# [params.awards]
# enable = true
#
# [[params.awards.list]]
# name = "Award Lorem Ipsum"
# body = "Microsoft lorem ipsum"
# date = "2019"
# [[params.awards.list]]
# name = "Award Donec Sodales"
# body = "Oracle Aenean"
# date = "2017"


[params.languages]
enable = true

[[params.languages.list]]
name = "Italian"
level = "Native"
[[params.languages.list]]
name = "English"
level = "C1"
[[params.languages.list]]
name = "Chinese"
level = "A1"


[params.interests]
enable = true
[[params.interests.list]]
name = "Music"
[[params.interests.list]]
name = "Videogames"
[[params.interests.list]]
name = "Cooking"
[[params.interests.list]]
name = "Inline skating"


[params.summary]
enable = true
text = """
Write your summary here. YourLorem ipsum dolor sit amet, consectetur adipiscing elit.
Integer quis pulvinar enim. Nullam condimentum mollis eros, a maximus turpis venenatis sit amet.
Aliquam sit amet velit dolor. Donec ornare, lacus id porttitor tincidunt, turpis
lorem mollis augue, sed mollis augue ipsum eu arcu. Nulla id augue erat.
Nunc in consectetur orci, eu molestie orci.
Duis nunc quam, viverra vel tristique a, lacinia mattis dolor.
"""


[params.experience]
enable = true

[[params.experience.list]]
title = "Backend developer"
dates = "07/07/2017 – in corso"
company = "B company"
details = """
Sed non molestie enim. Donec eu vulputate nisi, id semper tellus. Nam a quam eget lacus sagittis pulvinar.
Morbi elementum tincidunt erat vitae pretium.
Duis varius odio sit amet justo bibendum, vel mattis ante fringilla. Sed ac sem nisi.
Nam tempus ornare ante vel venenatis. Nulla pharetra libero non nulla congue, in vehicula neque tempor.
"""

[[params.experience.list]]
title = "\"Full\" stack developer"
dates = "09/2016 – 07/07/2017"
company = "A company"
details = """
Nullam mattis enim sed ultrices volutpat. Praesent euismod velit turpis, nec euismod urna maximus in.
Nulla vel posuere ex. Quisque varius pharetra massa, quis tincidunt dui tristique euismod.
Maecenas cursus viverra aliquam. Vivamus a quam luctus, commodo justo vitae, maximus nibh.
Vivamus in ipsum sed eros pharetra molestie.
Ut justo est, vulputate non eros id, consequat pulvinar ante. Sed nec ipsum augue.
"""


[params.projects]
enable = true

[[params.projects.list]]
title = "AwesomeCloud"
meta = " My own self-hosted cloud infrastructure"
tagline = """
Integer tempor sed magna id mollis.
Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
Praesent a nibh ultricies, posuere odio eu, sagittis justo.
Nunc id nulla quis augue egestas pretium eu eu dolor. Pellentesque enim ipsum, porta nec sapien et,
dignissim semper lacus. Aenean non pharetra est, at scelerisque ligula. Nullam euismod semper mauris,
sit amet auctor nisl scelerisque non. Nulla ullamcorper mi ac orci dapibus placerat.
"""


# [params.information]
# enable = true
#
# [[params.information.list]]
# title = "Papers"
# [[params.information.list.items]]
# details = "2018 · Lorem Ipsum"
# [[params.information.list.items]]
# details = "2016 · Sed Fringilla"
# [[params.information.list]]
# title = "Interests"
# details = "Climbing, Snowboarding, Photography, Travelling"


[params.social]
enable = true

[[params.social.list]]
icon = "fab fa-mastodon"
url = "https://mastodon-social/user"
title = "@username"
[[params.social.list]]
icon = "fab fa-twitter"
url = "https://twitter.com/username"
title = "@username"
[[params.social.list]]
icon = "fab fa-spotify"
url = "https://open.spotify.com/user/username"
title = "username"

[params.footer]
enable = true
copyright = "Gabriele Lucci"
